[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1C5bL1iEyNdjPJBEPgCTW4ZWIDBSmo8Dj6vOLvunpMmg/edit?usp=sharing"

[connections]
google_script_url = "https://script.google.com/macros/s/AKfycbzlcbiaSulZfjGgF45PBpsM5x15PGMrwwvZGuk0HGn4RkqgLrKGXs2E8VTSMs9sDjRMtA/exec"